# Generated by Django 5.1 on 2024-09-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaapp', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='licensing_document',
            field=models.FileField(blank=True, null=True, upload_to='licensing_docs/'),
        ),
    ]
