# Generated by Django 5.1 on 2024-10-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaapp', '0011_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_info',
            field=models.TextField(blank=True),
        ),
    ]
