# Generated by Django 5.1 on 2024-10-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaapp', '0025_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
